# Generated by Django 5.0.7 on 2024-07-31 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_rename_email_student_emil_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='emil',
            new_name='email',
        ),
    ]
