# Generated by Django 5.0.7 on 2024-08-01 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_remove_student_regno_student_admission_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
    ]
