# Generated by Django 5.0.7 on 2024-08-01 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_remove_student_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='admission_no',
            new_name='regno',
        ),
    ]
